addSbtPlugin("com.eed3si9n"     % "sbt-buildinfo"       % "0.13.1")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"         % "0.6.4")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"        % "2.5.2")
addSbtPlugin("com.github.sbt"   % "sbt-native-packager" % "1.10.4")
addSbtPlugin("com.eed3si9n"     % "sbt-assembly"        % "2.3.0")
