name: Build
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Test and Assembly
    runs-on: ubuntu-latest
    container:
      image: eed3si9n/sbt:jdk11-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: sbt test
      - name: Assembly JAR
        run: sbt cli/assembly
      - uses: actions/upload-artifact@v2
        with:
          name: kprojekt-cli.jar
          path: target/kprojekt-cli.jar

  release_jar:
    name: jar-image
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: ./
      - name: Release Jar
        uses: softprops/action-gh-release@v1
        with:
          files: 'artifact/kprojekt-cli.jar'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
