name: Build
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Test and Assembly
    runs-on: ubuntu-latest
    container:
      image: hseeberger/scala-sbt:17.0.2_1.6.2_2.13.8
    steps:
      - uses: actions/checkout@v2
      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-cache-${{ hashFiles('*.sbt') }}-${{ hashFiles('project/*') }}
      - name: Cache SBT Coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier/v1
          key: ${{ runner.os }}-sbt-coursier-cache-${{ hashFiles('*.sbt') }}-${{ hashFiles('project/*') }}
      - name: Run tests
        run: sbt test
      - name: Assembly JAR
        run: sbt cli/assembly
      - uses: actions/upload-artifact@v2
        with:
          path: target/kprojekt-cli.jar
      - uses: actions/upload-artifact@v2
        with:
          path: res/graalvm/

  release_jar:
    name: Release Jar
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: ./
      - name: Release artifact
        uses: softprops/action-gh-release@v1
        with:
          files: 'artifact/kprojekt-cli.jar'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release_nix:
    name: Build native images
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Env
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          gu --version
          native-image --version

      - uses: actions/download-artifact@v2
        with:
          path: ./

      - name: Create native image
        run: |
          native-image \
            --verbose \
            --initialize-at-build-time \
            --no-fallback \
            --allow-incomplete-classpath \
            -H:+ReportUnsupportedElementsAtRuntime \
            -H:+ReportExceptionStackTraces \
            -jar "./artifact/kprojekt-cli.jar" "kprojekt-cli"

      - name: Create tarball
        run: tar -zcvf "kprojekt-cli-${{ matrix.os }}.tar.gz" kprojekt-cli

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: helloworld-${{ matrix.os }}
          path: kprojekt-cli-${{ matrix.os }}.tar.gz
