name: Build
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'sbt'
      - name: Run tests
        run: sbt test

  release_nix:
    name: Build native images
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '19'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Env
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          gu --version
          native-image --version

      - name: Create native image
        run: |
          ./native-image-build.sh

      - name: Create tarball
        run: tar -zcvf "kprojekt-cli-${{ matrix.os }}.tar.gz" -C cli/target/graalvm-native-image/ ./kprojekt-cli

      - name: Release artifact
        uses: softprops/action-gh-release@v1
        with:
          files: 'kprojekt-cli-${{ matrix.os }}.tar.gz'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
